[workspace]
members = [ 
  "twitch_chat_tracker",
  "app_config", 
  "database_connection", 
  "report_generator", 
  "entities", 
  "entity_extensions",
  "migration", 
  "nightly_checks",
  "backend", 
  "spanix_scrubber", 
]
resolver = "3"
